server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'rinformatiks'
    url:  jdbc:postgresql://localhost:5432/customer
    password: 'password'
    jpa:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: 'true'
      properties:
        hibernate:
          dialect:  org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
